// <auto-generated />
namespace ehaiker.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Administrator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Administrator));
        
        string IMigrationMetadata.Id
        {
            get { return "201905151341569_Administrator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
