// <auto-generated />
namespace ehaiker.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class KefuServiceStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KefuServiceStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201905151229302_KefuServiceStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
