// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ehaiker;

namespace ehaikerv202010.Migrations
{
    [DbContext(typeof(EhaikerContext))]
    partial class EhaikerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ehaiker.Auth.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<int>("IsValidatedOK");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("GroupTable");
                });

            modelBuilder.Entity("ehaiker.Auth.GroupPermissionBinder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ControllerNo");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("OwnPermissions");

                    b.HasKey("Id");

                    b.ToTable("GroupBinderTable");
                });

            modelBuilder.Entity("ehaiker.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action");

                    b.Property<string>("ChineseActionName");

                    b.Property<string>("Controller");

                    b.Property<string>("Description");

                    b.Property<int>("GlobalNo");

                    b.Property<int>("ShowInManagerBar");

                    b.Property<int>("VisitLevel");

                    b.Property<int>("isGet");

                    b.HasKey("Id");

                    b.ToTable("PermissionTable");
                });

            modelBuilder.Entity("ehaiker.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description");

                    b.Property<int>("IsValidatedOK");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("RoleTable");
                });

            modelBuilder.Entity("ehaiker.Auth.RolePermissionBinder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ControllerNo");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("OwnPermissions");

                    b.HasKey("Id");

                    b.ToTable("RoleBinderTable");
                });

            modelBuilder.Entity("ehaiker.ChatRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Time");

                    b.Property<string>("customerContent");

                    b.Property<int>("customerId");

                    b.Property<string>("kfContent");

                    b.Property<int>("kfUserId");

                    b.HasKey("RecordId");

                    b.ToTable("chatRecords");
                });

            modelBuilder.Entity("ehaiker.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserName");

                    b.Property<int>("customerId");

                    b.Property<string>("headImg");

                    b.Property<int>("isOnline");

                    b.Property<int>("kfUserId");

                    b.HasKey("Id");

                    b.ToTable("kefu_customers");
                });

            modelBuilder.Entity("ehaiker.GameType", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("GameId");

                    b.ToTable("GameTypes");
                });

            modelBuilder.Entity("ehaiker.KefuServiceStatus", b =>
                {
                    b.Property<int>("kfUserIndex")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("CurrentPeople");

                    b.Property<int>("GroupId");

                    b.Property<string>("UserName");

                    b.Property<int>("isOnline");

                    b.Property<int>("kfUserId");

                    b.HasKey("kfUserIndex");

                    b.ToTable("kefu_StatusService");
                });

            modelBuilder.Entity("ehaiker.Models.CommentModel", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("GameID");

                    b.Property<string>("GameName");

                    b.Property<int>("GameStrateID");

                    b.Property<int>("IsChecked");

                    b.Property<int>("UserId");

                    b.Property<string>("UserName");

                    b.Property<string>("comment");

                    b.HasKey("CommentID");

                    b.ToTable("CommentTable");
                });

            modelBuilder.Entity("ehaiker.Models.GameModel", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Announcer");

                    b.Property<int>("AuthorID");

                    b.Property<DateTime>("EndTime");

                    b.Property<int>("Gametype");

                    b.Property<string>("ImgDescUri");

                    b.Property<string>("ImgHoverUri");

                    b.Property<int>("IsIdentified");

                    b.Property<string>("ItemName");

                    b.Property<string>("Keywords");

                    b.Property<DateTime>("MineTime");

                    b.Property<string>("ReferAthor");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("TopLevel");

                    b.Property<string>("gameDescription");

                    b.Property<float>("grade");

                    b.Property<string>("producer");

                    b.Property<string>("resourcefrom");

                    b.Property<string>("supporter");

                    b.Property<string>("targetUri");

                    b.HasKey("ItemID");

                    b.ToTable("GameLists");
                });

            modelBuilder.Entity("ehaiker.Models.MemberShip", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("GroupId");

                    b.Property<string>("Icon");

                    b.Property<DateTime?>("LastSignTime");

                    b.Property<string>("LoginGuid");

                    b.Property<string>("LoginIP");

                    b.Property<DateTime?>("LoginTime");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(11);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int>("SignCount");

                    b.Property<string>("UserGuid");

                    b.Property<string>("UserName");

                    b.Property<int>("VIPLevel");

                    b.Property<int>("nStatus");

                    b.Property<string>("sPermission");

                    b.HasKey("UserId");

                    b.ToTable("MemShips");
                });

            modelBuilder.Entity("ehaiker.Models.MemberShipInfomation", b =>
                {
                    b.Property<int>("IndexId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IdentityCard");

                    b.Property<decimal>("TMoney");

                    b.Property<decimal>("UMoney");

                    b.Property<string>("UserGuid");

                    b.Property<int>("isIdentityValid");

                    b.Property<int>("isMailValid");

                    b.Property<int>("isValid");

                    b.HasKey("IndexId");

                    b.ToTable("MemberShipInfomation");
                });

            modelBuilder.Entity("ehaiker.Models.PaybillApproveModel", b =>
                {
                    b.Property<int>("PayBillApproveID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApproveDeleteMask");

                    b.Property<string>("ApproveForWhat");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("PayBillID");

                    b.Property<DateTime>("PayForDateTime");

                    b.Property<int>("PayState");

                    b.Property<int>("PayType");

                    b.Property<int>("PayValue");

                    b.HasKey("PayBillApproveID");

                    b.ToTable("PayBillApproveModels");
                });

            modelBuilder.Entity("ehaiker.Models.PaybillModel", b =>
                {
                    b.Property<int>("PayBillID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("PayDeleteMask");

                    b.Property<DateTime>("PayForDateTime");

                    b.Property<string>("PayForWhat");

                    b.Property<string>("PayIdentity");

                    b.Property<int>("PayState");

                    b.Property<int>("PayType");

                    b.Property<int>("PayValue");

                    b.Property<int>("UserId");

                    b.HasKey("PayBillID");

                    b.ToTable("PayBillModels");
                });

            modelBuilder.Entity("ehaiker.Models.SupplierModel", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImgDescUri");

                    b.Property<string>("ImgHoverUri");

                    b.Property<string>("ItemName");

                    b.Property<string>("hrefUri");

                    b.HasKey("ItemID");

                    b.ToTable("SupplierItems");
                });

            modelBuilder.Entity("ehaikerv202010.Models.Administrator", b =>
                {
                    b.Property<int>("AdministratorID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("GroupId");

                    b.Property<string>("LoginGuid");

                    b.Property<string>("LoginIP");

                    b.Property<DateTime?>("LoginTime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("UserGuid");

                    b.Property<string>("nickname");

                    b.Property<string>("sPermission");

                    b.HasKey("AdministratorID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("ehaikerv202010.Models.GameStrategies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("GameId");

                    b.Property<int>("IsIdentified");

                    b.Property<int>("IsUnVisible");

                    b.Property<DateTime>("LastEditTime");

                    b.Property<int>("Rank");

                    b.Property<string>("ReferAthor");

                    b.Property<string>("ReferUri");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("UserGuid");

                    b.Property<int>("VipLevel");

                    b.Property<int>("lookupvalue");

                    b.Property<int>("readers");

                    b.Property<int>("toplevel");

                    b.HasKey("Id");

                    b.ToTable("GameStrategs");
                });

            modelBuilder.Entity("ehaikerv202010.Models.ItBlogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("IsIdentified");

                    b.Property<int>("IsUnVisible");

                    b.Property<DateTime>("LastEditTime");

                    b.Property<int>("Rank");

                    b.Property<string>("ReferAthor");

                    b.Property<string>("ReferUri");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("UserGuid");

                    b.Property<int>("VipLevel");

                    b.Property<int>("blogtype");

                    b.Property<int>("lookupvalue");

                    b.Property<int>("readers");

                    b.Property<int>("toplevel");

                    b.HasKey("Id");

                    b.ToTable("ItBlogSets");
                });

            modelBuilder.Entity("ehaikerv202010.Models.MyGameLibs", b =>
                {
                    b.Property<int>("IndexID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GameID");

                    b.Property<int>("Gametype");

                    b.Property<string>("ItemName");

                    b.Property<string>("UserGuid");

                    b.HasKey("IndexID");

                    b.ToTable("MyGames");
                });

            modelBuilder.Entity("ehaikerv202010.Models.MyGameStrage", b =>
                {
                    b.Property<int>("IndexID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GameID");

                    b.Property<int>("Gametype");

                    b.Property<string>("ItemName");

                    b.Property<string>("UserGuid");

                    b.HasKey("IndexID");

                    b.ToTable("MyGameStrages");
                });

            modelBuilder.Entity("ehaikerv202010.Models.MyItBlogModel", b =>
                {
                    b.Property<int>("IndexID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlogID");

                    b.Property<string>("ItemName");

                    b.Property<string>("UserGuid");

                    b.Property<int>("blogtype");

                    b.HasKey("IndexID");

                    b.ToTable("MyItBlogs");
                });

            modelBuilder.Entity("ehaikerv202010.Models.NewsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Announcer");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<int>("IsUnVisible");

                    b.Property<DateTime>("LastEditTime");

                    b.Property<int>("NewsTypeId");

                    b.Property<int>("Rank");

                    b.Property<string>("ReferAthor");

                    b.Property<DateTime>("ReleaseTime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int>("readers");

                    b.Property<int>("toplevel");

                    b.HasKey("Id");

                    b.ToTable("WebNewses");
                });
#pragma warning restore 612, 618
        }
    }
}
